import pygame
pygame.font.init()

#Window Settings
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 480
FPS = 60
SONGS_SCROLL_SPEED = 30

#OBJECTS W/H
TOP_BAR_HEIGHT = 60
TOP_BAR_RECT = (0 , 0 , SCREEN_WIDTH , TOP_BAR_HEIGHT)

KEYBOARD_HEIGHT = 100

SAVE_POPUP_WIDTH = 300
SAVE_POPUP_HEIGHT = 150

SAVE_BUTTON_WIDTH = SAVE_POPUP_WIDTH / 3
SAVE_BUTTON_HEIGHT = SAVE_POPUP_HEIGHT / 3

PLAYBACK_BUTTONS_SIZE = TOP_BAR_HEIGHT /2
PLAYBACK_BUTTONS_SPACING = 10
PLAYBACK_BUTTONS_Y = (TOP_BAR_HEIGHT//2) - (PLAYBACK_BUTTONS_SIZE//4)
RECORD_BUTTON_RECT = (0, 0, TOP_BAR_HEIGHT, TOP_BAR_HEIGHT)
TO_SONGS_BUTTON_RECT =(SCREEN_WIDTH - TOP_BAR_HEIGHT, 0 , TOP_BAR_HEIGHT , TOP_BAR_HEIGHT)
SONGS_BACK_BUTTON_RECT = RECORD_BUTTON_RECT

SONGS_CONTAINER_WIDTH = 500
SONGS_CONTAINER_HEIGHT = 300
SONGS_CONTAINER_X = (SCREEN_WIDTH // 2) - (SONGS_CONTAINER_WIDTH // 2)
SONGS_CONTAINER_Y = (SCREEN_HEIGHT / 2) - (SONGS_CONTAINER_HEIGHT / 2)
SONGS_CONTAINER_RECT = (SONGS_CONTAINER_X, SONGS_CONTAINER_Y, SONGS_CONTAINER_WIDTH , SONGS_CONTAINER_HEIGHT)

SONG_ITEM_HEIGHT = 50
SONG_ITEM_SPACING = 10
SONG_ITEM_TOTAL_HEIGHT = SONG_ITEM_HEIGHT + SONG_ITEM_SPACING

SONG_BUTTON_SIZE = 30
SONG_PLAY_X = SONGS_CONTAINER_X + SONGS_CONTAINER_WIDTH - (2 * SONG_ITEM_SPACING) - SONG_BUTTON_SIZE
SONG_DOWNLOAD_X = SONG_PLAY_X - SONG_ITEM_SPACING - SONG_BUTTON_SIZE
SONG_DELETE_X = SONGS_CONTAINER_X - SONG_ITEM_SPACING - SONG_BUTTON_SIZE


#Pixels/Sec
NOTE_SPEED = 300

# Colors
LIGHT_PURPLE = (100, 70, 180)
DARK_PURPLE = (30, 24, 80)
INTENSE_PURPLE = (58, 24, 148) 
VERY_INTENSE_PURPLE = (55, 7, 181)
PURPLE = (51, 40, 130)
BLACK = (0, 0, 0)
WHITE = (240, 240, 240)
BG_COLOR = (15, 15, 20)
TOP_BAR_COLOR = (30, 30, 40)
SAVE_POPUP_COLOR = TOP_BAR_COLOR
SONGS_CONTAINER_COLOR = TOP_BAR_COLOR
TEXT_COLOR = WHITE
SONG_ITEM_COLOR = (40, 40, 50)  
SONG_ITEM_SELECTED_COLOR = LIGHT_PURPLE
SONG_PLAY_COLOR = (51, 33, 99)
SONG_DOWNLOAD_COLOR = SONG_PLAY_COLOR
SONG_DELETE_COLOR = SONG_PLAY_COLOR


# Key Colors
KEY_WHITE_IDLE = (255, 255, 255)
KEY_WHITE_PRESSED = LIGHT_PURPLE # Bright Purple

KEY_BLACK_IDLE = (30, 30, 30)
KEY_BLACK_PRESSED = PURPLE # Dark Purple

KEY_WHITE_CORRECT = (11, 176, 110)
KEY_WHITE_WRONG = (176, 11, 74)

KEY_BLACK_CORRECT = (6, 87, 54)
KEY_BLACK_WRONG = (130, 8, 55)

KEY_WHITE_OUTLINE = (100, 100, 100)

# Note Colors (Matching pressed keys)
NOTE_WHITE_COLOR = KEY_WHITE_PRESSED
NOTE_BLACK_COLOR = INTENSE_PURPLE

# Note Name
NOTE_NAMES = ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B",]
AUDIO_LATENCY = 0

# FONTS
SAVE_POPUP_FONT = pygame.font.SysFont("Arial", 24, bold = True)
VIS_TITLE_FONT = pygame.font.SysFont("Arial", 12, bold = True)
SONGS_TITLE_FONT = pygame.font.SysFont("Arial", 40, bold=True)
SONGS_LIST_FONT = pygame.font.SysFont("Arial", 20)
